const MOBILE_BREAKPOINT = 768;

const SCROLL_OFFSET = 350;

const SCROLL_GAP = 15;

const TRUNCATE_LENGTH = {
  TABLE: 70,
  ADMIN: 65,
} as const;

const MAX_CSV_ROWS_DEFAULT = process.env.NEXT_PUBLIC_MAX_ROW_CSV ?? 10000;

const GRACEFUL_SHUTDOWN_MS = 5000;

const DEFAULT_DATE_RANGE_DAYS = 7;

const CHARACTER_LIMIT = 1000;

export {
  CHARACTER_LIMIT,
  DEFAULT_DATE_RANGE_DAYS,
  GRACEFUL_SHUTDOWN_MS,
  MAX_CSV_ROWS_DEFAULT,
  MOBILE_BREAKPOINT,
  SCROLL_GAP,
  SCROLL_OFFSET,
  TRUNCATE_LENGTH,
};
