const AINoticeList: string[] = [
  "This tool uses AI to help you find Universal Learning guidance.",
  "It searches the guidance and produces summaries in response to your questions.",
  "AI-generated summaries may contain errors. You must use the Universal Learning guidance to check they are accurate before acting on them.",
  "The summaries generated by this tool do not replace DWP’s official policy or guidance.",
  "Work coaches should use this tool responsibly and in accordance with DWP policies and procedures.",
];

export { AINoticeList };
