fragment-version-check:
  extends: .fragment-version-check-template
required-fragment-check:
  extends: .required-fragment-check-template
gitleaks:
  extends: .gitleaks-template
shell-check:
  extends: .shell-check-template
todo-check:
  extends: .todo-check-template
lint-source:
  extends: .lint-source-template
docker-lint:
  extends: .docker-lint-template
unit-test:
  extends: .unit-test-template
push-to-ecr-prodaws:
  extends: .push-to-ecr
  when: manual
stryker-mutation:
  allow_failure: true
  extends: .stryker-mutation-template
  needs: []
node-outdated:
  allow_failure: true
  extends: .node-outdated-template
docker-build:
  extends: .docker-build-template
trivy-container:
  extends: .trivy-container-base
sast-container:
  extends: .sast-container-base
container-test-command:
  extends: .container-test-template
create-project-badges:
  extends: .create-project-badges-template
nonprod-push-to-ecr:
  extends: .push-to-ecr
  when: manual
sonar-scanner:
  extends: .sonar-scanner-base
test-coverage:
  extends: .test-coverage-template
node-audit:
  extends: .node-audit-base
node-audit-production:
  extends: .node-audit-production-base
  allow_failure: true
create-develop-morning-schedule:
  extends: .add-schedule-template
  variables:
    SCHEDULE_NAME: Morning-Develop-CI-Build
    SCHEDULE_BRANCH: develop
    SCHEDULE_CRON: 30 05 * * *
    RANDOMIZE_MINS: "true"